eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    password: project-service
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: project-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      dialect: H2DialectCustom

